### ISSUE TITLE
Tweak color scale

### ISSUE THREAD

**Issue by espehon** [espehon/clocky-cli#12]
The original color scale was made for an Ubuntu theme with a burgundy-like color as its 'magenta'.
If most themes use purple as their magenta, then the color scale should put purple between white and blue.

**Comment by TeenaBatra** [comment]
Hi @espehon, I am a beginner in python and want to give this issue a try. I tried to run this in my local, but this is the output it is showing:
You are not clocked in.    [Total: 0]    8 Hours Remaining
Last entry: No log found...

Process finished with exit code 0
Could you please help me how can I run this to understand its working? - Thank you!

**Comment by espehon** [comment]
Hi @TeenaBatra it looks like it is working. Try passing the `-?` or `--demo` option to see more of the program. You can also try `-t` to see if the clocking in and out function works.

As for this issue, I just marked the function where the color scale is defined (line 665 I think) if you want to give it a shot. The trick will be reordering the colors. Use `-c` to output the colored chart for testing. 

Please keep in mind that this program was my first "installable" program and so it is very messy.

**Comment by TeenaBatra** [comment]
Hi @espehon, Thanks for clarification!
I am thinking of tweaking this color scale like this:
![Screenshot 2023-02-12 at 6 33 53 PM](https://user-images.githubusercontent.com/77160277/218312920-23b14524-44a7-43cb-8d1a-ce5740b9738a.png)
I took reference from this page: https://htmlcolorcodes.com/color-chart/
What do you think? 
Please let me know if you have any suggestions!

**Comment by espehon** [comment]
It seems you figured it out, @TeenaBatra 

Here is how I had originally intended for the scale to look:
![image](https://user-images.githubusercontent.com/117602649/218335729-736fc70e-82d0-4a35-98b0-506de2a740dc.png)

However, this is how it looks on a theme where magenta is set to purple (which I think is the norm):
![image](https://user-images.githubusercontent.com/117602649/218335871-f2719db1-7147-4ef5-9111-007ac3c6108b.png)

My plan was to simply place the magenta between the white and blue segments, and then rescale the numbers so that the green will still line up with the "target hours".

I went from blue to red as a "go from cold to warm" color scheme.
That being said, I like your scale. It seems to encourage working a little overtime. Maybe (in the future) the scale can be user-defined.

**Comment by espehon** [comment]
It looks like the color scale can be defined in the ini file so I created #14 
This fix will be for the default scale
